targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      
      build_version:
        options:
          output: lib/versioning/build_version.dart