name: habit_tracker
description: A Very Good Project created by Very Good CLI.
version: 1.0.5+5
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  build_version: ^2.1.1
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.4.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  fl_chart: ^0.70.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  hive_ce: ^2.9.0
  hive_ce_flutter: ^2.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  logger: ^2.5.0
  mesh_gradient: ^1.3.8
  toastification: ^2.3.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  hive_ce_generator: ^1.8.1
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
